### ISSUE TITLE
Community or Help

### ISSUE THREAD

**Issue by cnyanzi** [dluxem/LiberumASP#1]
I recently discovered Liberum Help desk. I decided to test it before i recommended it for a solution. After setting it up I started to test and I started to run into issues. It throws a lot of errors. Most of them ODBC driver related. The interesting thing is I could have added a user or edited a user five minutes ago and I try to edit another user then I got from a process that was successful earlier throwing an error.
With some of the errors I deducted that it's a session expiry issue, which I don't understand why the session expires that quick. 
My major problem is an error I was getting because the server was denying access to certain directories. The issue is I had actually "Configured ASP to allow Parent Paths", but I still get the error suggesting that...The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable. I know I could get this if parent paths were not enabled. I have permissions inherited from the parent directory. All sub folders have modify, read and write permissions for authenticated users. 
Do you have a community were I can find some help? Or can you help?

**Comment by cnyanzi** [comment]
I was really hoping that you'd spare a minute and give me some help. I have actually worked out most of the things explained in the last thread but now I am wondering...In all the configurations I do not have settings for authenticating to the SMTP Server. Using ASPEmail i have tried to send a test email and I get 
![connecttion error](https://cloud.githubusercontent.com/assets/982633/6466050/34217ba0-c182-11e4-85c1-9389d0e7067c.PNG)
Would I have to add keys in the config file to maneuver this or how can I fix it? Any help!

**Comment by cnyanzi** [comment]
Never mind that last thread either. I did some more digging and found the user guide for ASPEmail and also the public file that has all these settings and wala I am way over that hump.

**Comment by dluxem** [comment]
I'm happy were were able to solve the problem. I'm working on a final build of Liberum (ASP version) that will include `CDOSYS` by default which will simplify the SMTP setup.
